debug: false # 내용이 너무 많아서 false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.brand13.board01: debug
    org.springframework.web.servlet: debug # request / response log
    org.hibernate.type.descriptor.sql.BasicBinder: trace #db param log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true
    username: brand13
    password: kind0314
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:h2:~/test
    # username: sa
    # driver-class-name: org.h2.Driver
  jpa:
    database: mysql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # ddl-auto: create #data.sql? ????? ???.
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.default_batch_fetch_size: 100 # 최대 100개의 bulk로 select
  h2:
    console:
      enabled: false
  # sql:
  #   init:
  #     mode: always # data.sql ??? ?? ??? ???(embeded: ??????.. Always: ???)
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  thymeleaf3:    # 내가 만든 속성. ThymeleafConfig.java
    decoupled-logic: true
  web:
    resources:
      static-locations:
      - file:src/main/resources/static/
  devtools: 
    livereload:
      enabled: false     
  output:
    ansi:
      enabled: always     
---

spring:
  config:
    activate:
      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#    sql.init.mode: always
#    test.database.replace: none